server:
  port: 3000

spring:
  # 데이터베이스 설정
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: PROJECT
    password: _aA123456

  # JPA 설정
  jpa:
    properties:
      hibernate:
        # 실행되는 쿼리를 콘솔에 출력
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.OracleDialect
    hibernate:
      ddlAuto: create

  # 파일 업로드 설정
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 40MB

  # 정적 자원 설정(CSS, JS, 이미지), 11.20 web: 추가
  web:
    resources:
      staticLocations: file:src/main/resources/static/

  # 라이브 리로드 설정(서버가 터지므로 제거)


  # 타임리프 설정 -> 11.20 cache: true로 변경, file:src/main/resources/templates/ -> classpath:/templates/ 로변경
  thymeleaf:
    cache: true
    prefix: classpath:/templates/

  # 11.20   flyway:
  #    enabled: true 제거


file:
  upload:
    path: C:/uploads/
    url: /uploads/

# 로거 설정
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace