server:
  port: 3000

# 항상 콜론으로 끝날때는 스페이스바(공백) 넣어주기 - > 안넣으면 인식안함

spring:
  # 프로필 설정
  profiles:
    active: dev

  # 데이터베이스 설정
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl    #orcl -> xe사용자는 xe로 변경
    username: PROJECT
    password: _aA123456

  # 파일 업로드 설정
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 40MB

  # 정적 자원 설정(CSS, JS, 이미지 - 서버를 리스타트하지않아도 css파일 바로 바로 적용됌 - 정적(static))
  resources:
    staticLocations: file:src/main/resources/static/

  # 라이브 리로드 설정
  devtools:
    livereload:
      enabled: true

  # 타임리프 설정
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/


# 파일설정
file:
  upload:
    path: C:/uploads/
    url: /uploads/

# 로거 설정
logging:
  level:
    org:
      springframework:
        jdbc: trace
